### ISSUE TITLE
It doesn't install in Windows 10 21H2

### ISSUE THREAD

**Issue by Zero3K** [smokingpc/glendronach#1]
![image](https://github.com/smokingpc/glendronach/assets/6194332/57ebb56a-74f9-49bf-a725-245a15ade1ea)

[setupapi.dev.log](https://github.com/smokingpc/glendronach/files/11508974/setupapi.dev.log)

**Comment by Zero3K** [comment]
It turns out that I needed to run the following in a Command Prompt and reboot in order to get the driver to install:

Bcdedit -set loadoptions  DDISABLE_INTEGRITY_CHECKS
bcdedit.exe -set TESTSIGNING ON

**Comment by smokingpc** [comment]
Hi
Sorry for late reply.

If you want to install driver on windows without WHQL certificate, you have to turn on 2 setting to skip integraty check.
Please open dos console with administrator privilege and execute following 2 commands:

Bcdedit -set loadoptions DDISABLE_INTEGRITY_CHECKS
bcdedit.exe -set TESTSIGNING ON

After turn on them, please reboot to make them work.
And after this, all driver you installed without signature will pop a red dialogbox to ask you "are you sure to install it?"

Roy

**Comment by Zero3K** [comment]
You should mention those instructions in its README.
